# Generated by Django 5.2.8 on 2025-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the post (max 300 characters)', max_length=300),
        ),
    ]
